### ISSUE TITLE
How to receive the credentials with wallet-connect ?

### ISSUE THREAD

**Issue by amarts** [uport-project/daf-mobile#143]
This arises after merging PR #142 

We were using Trust-graph to fetch the messages when they got issued from a webapp asynchronously. Now with wallet-connect in picture, is there any change in WebApp (daf based) you foresee? Should we scan the credential to get it into mobile wallet? How does issuing of credentials work?

**Comment by jasonhealy** [comment]
The latest PR brings wallet connect support to the daf-mobile stack.  We have also remove the TrustGraph plugin by default but you can keep that in your instance if you wish to keep TG specific flows. It will still work as before but it is not something we officially recommend for large scale production use due to its public only nature. 

TrustGraph provided us both a transport layer and also served as a backup solution to make development of the framework easier. For the transport layer we now recommend using a base combination of WalletConnect and DidComm under any of your own custom messaging layers. The backup part we are currently working on but looking to implement a basic iCloud/GDrive backup feature for now. 

An initial full example playground using WalletConnect on the dapp side will be provided in the coming days. 

Let us know if you have any issues with the update!

**Comment by amarts** [comment]
Thanks! This info is helpful for now. Will get back with any further questions if any...

**Comment by jasonhealy** [comment]
@amarts check out our wallet connect demo. This works with the latest version of daf-mobile. https://github.com/uport-project/dafhub

**Comment by amarts** [comment]
Thanks @jasonhealy! Will check this out soon. Having a working setup helps us to understand better :+1:
